### ISSUE TITLE
Axie Marketplace: Send Offer: message signature

### ISSUE THREAD

**Issue by YouHeDad** [alexx855/axie-ronin-ethers-js-tools#5]
Hello again!

Ok, so this is not really an issue.  But more of a question.

I am reworking the 'create-order' code to send offers.  It uses the graphQL mutation, createOrder();

I am getting hung up on the signature generation though.  I am not sure how to retrieve the message that App.axie marketplace generates, for us to sign when we make an offer.

I have tried manually generating it, then running:
const signature = await wallet._signTypedData(domain, types, orderData)

Their serverside signature verification must be using a bit of a different method, or my fields aren't exact, and it's modifying the signature, (I.E startAt, nonce)

GraphQL error messages are pretty vague, so it's difficult to pinpoint which parameter is messing up the signature.  But the error from the mutate query is always, 'maker is not signer' - I have verified that the 'maker' field is indeed my address.

Any thoughts or ideas? *ponder*

Thanks!!
-M1nz

**Comment by alexx855** [comment]
Hello @YouHeDad 

`maker is not signer` is ambiguos and not always reveals what the real problem is, usually by my experience it means that your are sending the wrong/malformed data and that is one of the first test it does, and since it cannot get the maker it throws with that error.

Try to send an offer using the official app and decode the transaction data, then compare it with what you are sending.

If you need some help write to me on discord, i might add offers soon too.

**Comment by YouHeDad** [comment]
Oh,i was able to figure it out!
I wasn't keckkaking the signature correctly ♡♡
